launch:
  ros__parameters:
    joy: false
    planner: false

/**:
  ros__parameters:
    linear_max:
      vel: 1.0
      acc: 5.0
    angular_max:
      vel: 1.0
      acc: 5.0

icart_driver:
  ros__parameters:
    interval_ms: 100
